# Generated by Django 3.0.3 on 2020-04-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0003_auto_20200409_0957'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referencespacegeocode',
            table='referencespace_geocode',
        ),
        migrations.AlterModelTable(
            name='referencespacelocation',
            table='referencespace_location',
        ),
    ]
