# Generated by Django 3.0.3 on 2020-04-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0004_auto_20200409_1154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referencespacegeocode',
            table='stafdb_referencespace_geocode',
        ),
        migrations.AlterModelTable(
            name='referencespacelocation',
            table='stafdb_referencespace_location',
        ),
    ]
