# Generated by Django 3.0.3 on 2020-04-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0005_auto_20200409_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='active',
        ),
        migrations.RemoveField(
            model_name='referencespacelocation',
            name='active',
        ),
        migrations.AddField(
            model_name='referencespace',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='referencespacelocation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterModelTable(
            name='geocodesystem',
            table='stafdb_geocode_system',
        ),
    ]
