# Generated by Django 3.0.3 on 2020-04-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0006_auto_20200409_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodesystem',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stafdb.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='geocodesystem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
