# Generated by Django 3.0.3 on 2020-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0007_auto_20200409_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocode',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
