# Generated by Django 3.0.3 on 2020-04-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0008_geocode_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('is_separator', models.BooleanField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stafdb.ActivityCatalog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stafdb.Activity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='flowblocks',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_to', to='stafdb.Activity'),
        ),
        migrations.AlterField(
            model_name='flowblocks',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_from', to='stafdb.Activity'),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
