# Generated by Django 3.0.3 on 2020-04-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0009_auto_20200421_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='slug',
        ),
    ]
