# Generated by Django 3.0.3 on 2020-04-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0010_remove_activity_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeocodeSystem',
            new_name='GeocodeScheme',
        ),
        migrations.RenameField(
            model_name='geocode',
            old_name='system',
            new_name='scheme',
        ),
    ]
