# Generated by Django 3.0.3 on 2020-04-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0011_auto_20200422_1813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='geocodescheme',
            table='stafdb_geocode_scheme',
        ),
    ]
