# Generated by Django 3.0.3 on 2020-04-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0013_auto_20200422_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowblocks',
            name='diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='stafdb.FlowDiagram'),
        ),
    ]
