# Generated by Django 3.0.3 on 2020-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0014_auto_20200423_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodescheme',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
