# Generated by Django 3.0.3 on 2020-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0015_geocodescheme_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='geocodes',
            field=models.ManyToManyField(through='stafdb.ReferenceSpaceGeocode', to='stafdb.Geocode'),
        ),
    ]
