# Generated by Django 3.0.3 on 2020-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0017_auto_20200429_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycatalog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
