# Generated by Django 3.0.3 on 2020-04-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_license_photo'),
        ('stafdb', '0020_auto_20200429_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Photo'),
        ),
    ]
