# Generated by Django 3.0.3 on 2020-04-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0021_referencespace_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='photo',
        ),
    ]
