# Generated by Django 3.0.3 on 2020-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0023_referencespacesector_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocode',
            options={'ordering': ['depth', 'id']},
        ),
        migrations.AddField(
            model_name='flowblocks',
            name='destination_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flowblocks',
            name='origin_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
