# Generated by Django 3.0.3 on 2020-05-08 17:28

from django.db import migrations, models
import stafdb.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0026_uploadfile_uploadsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=stafdb.models.shapefile_directory),
        ),
    ]
