# Generated by Django 3.0.3 on 2020-05-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_workpiece_tags'),
        ('stafdb', '0027_auto_20200508_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stafdb.ReferenceSpace'),
        ),
    ]
