# Generated by Django 3.0.3 on 2020-05-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0028_auto_20200513_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
