# Generated by Django 3.0.3 on 2020-05-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0030_uploadsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
