# Generated by Django 3.0.3 on 2020-05-13 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0031_uploadsession_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
