# Generated by Django 3.0.3 on 2020-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0032_uploadsession_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='is_uploaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
