# Generated by Django 3.0.3 on 2020-05-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0033_uploadsession_is_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['id'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelTable(
            name='activity',
            table='stafdb_activity',
        ),
        migrations.AlterModelTable(
            name='activitycatalog',
            table='stafdb_activitycatalog',
        ),
        migrations.AlterModelTable(
            name='flowblocks',
            table='stafdb_flowblocks',
        ),
        migrations.AlterModelTable(
            name='flowdiagram',
            table='stafdb_flowdiagram',
        ),
        migrations.AlterModelTable(
            name='geocode',
            table='stafdb_geocode',
        ),
        migrations.AlterModelTable(
            name='material',
            table='stafdb_material',
        ),
        migrations.AlterModelTable(
            name='materialcatalog',
            table='stafdb_materialcatalog',
        ),
        migrations.AlterModelTable(
            name='referencespace',
            table='stafdb_referencespace',
        ),
        migrations.AlterModelTable(
            name='referencespacesector',
            table='stafdb_referencespacesector',
        ),
        migrations.AlterModelTable(
            name='sector',
            table='stafdb_sector',
        ),
        migrations.AlterModelTable(
            name='uploadfile',
            table='stafdb_uploadfile',
        ),
        migrations.AlterModelTable(
            name='uploadsession',
            table='stafdb_uploadsession',
        ),
    ]
