# Generated by Django 3.0.3 on 2020-05-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0034_auto_20200514_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
    ]
