# Generated by Django 3.0.3 on 2020-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0035_auto_20200514_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='activities',
            field=models.ManyToManyField(db_table='stafdb_sector_activities', to='stafdb.Activity'),
        ),
    ]
