# Generated by Django 3.0.3 on 2020-03-07 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='record',
        ),
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='record',
        ),
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.RemoveField(
            model_name='people',
            name='record',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='record',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='record',
        ),
        migrations.AddField(
            model_name='event',
            name='record_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='record_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='record_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='record_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='record_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            bases=('core.record',),
        ),
    ]
