# Generated by Django 3.0.3 on 2020-04-09 04:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_forummessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moocmodulequestion',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='moocmodulequestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.MOOCModule'),
        ),
        migrations.AlterField(
            model_name='moocmodulequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MOOCQuestion'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('hidden', models.BooleanField(db_index=True, default=False, help_text='Mark if tag is superseded/not yet approved/deactivated')),
                ('include_in_glossary', models.BooleanField(db_index=True, default=False)),
                ('parent_tag', models.ForeignKey(blank=True, limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
