# Generated by Django 3.0.3 on 2020-03-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200307_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='type',
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
