# Generated by Django 3.1.2 on 2020-11-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201108_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='part_of_project',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='record_ptr',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.DeleteModel(
            name='UploadSession',
        ),
    ]
