# Generated by Django 3.0.3 on 2020-04-09 04:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200409_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
