# Generated by Django 3.0.3 on 2020-03-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200307_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Record'),
        ),
    ]
