# Generated by Django 3.1.2 on 2020-11-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201122_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True)),
                ('end', models.DateField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'stafdb_timeperiod',
            },
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('ES', 'Spanish'), ('CH', 'Chinese'), ('FR', 'French'), ('GE', 'German'), ('NL', 'Dutch'), ('PT', 'Portuguese'), ('CT', 'Catalan'), ('OT', 'Other')], default='EN', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('material_name', models.CharField(blank=True, max_length=500, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_to', to='core.activity')),
                ('destination_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_to_space', to='core.referencespace')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_from', to='core.activity')),
                ('origin_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_from_space', to='core.referencespace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.libraryitem')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeperiod')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'db_table': 'stafdb_data',
            },
        ),
    ]
