# Generated by Django 3.0.3 on 2020-04-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200409_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='active',
        ),
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
