# Generated by Django 3.1.2 on 2020-11-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201122_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['timeframe__start', 'id']},
        ),
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
    ]
