# Generated by Django 3.0.3 on 2020-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200307_0510'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='site_slug'),
        ),
    ]
