# Generated by Django 3.1.2 on 2020-11-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201122_2007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='stafdb_data',
        ),
    ]
