# Generated by Django 3.0.3 on 2020-03-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200307_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
