# Generated by Django 3.0.3 on 2020-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_article_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
