# Generated by Django 3.1.2 on 2020-12-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201202_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='segment_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
