# Generated by Django 3.0.3 on 2020-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200420_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'In progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='target_finish_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
