# Generated by Django 3.1.2 on 2020-12-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_data_segment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataViz',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.record')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataviz', to='core.libraryitem')),
            ],
            bases=('core.record',),
        ),
    ]
