# Generated by Django 3.0.3 on 2020-03-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200307_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name_plural': 'people'},
        ),
    ]
