# Generated by Django 3.1.2 on 2020-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dataviz'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='synonyms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
