# Generated by Django 3.1.2 on 2020-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_unit_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_data_project',
            field=models.BooleanField(default=False),
        ),
    ]
