# Generated by Django 3.0.3 on 2020-04-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_video_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='researchgate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
