# Generated by Django 3.0.3 on 2020-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200422_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark if this is a project undertaken by our own members within our own website'),
        ),
    ]
