# Generated by Django 3.1.2 on 2020-12-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_is_data_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.record')),
                ('position', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('projects', models.ManyToManyField(to='core.Project')),
            ],
            bases=('core.record',),
        ),
    ]
