# Generated by Django 3.1.2 on 2020-12-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['year', 'position']},
        ),
    ]
