# Generated by Django 3.0.3 on 2020-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0013_auto_20200312_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='site',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
