# Generated by Django 3.0.3 on 2020-04-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag_is_public'),
        ('core', '0013_project_is_internal'),
    ]

    operations = [
    ]
