# Generated by Django 3.1.2 on 2020-12-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201221_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.Project'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(help_text='Do NOT change this if the course is already published', max_length=255, null=True),
        ),
    ]
