# Generated by Django 3.0.3 on 2020-03-12 20:12

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200312_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledesign',
            old_name='background',
            new_name='header_background',
        ),
        migrations.AddField(
            model_name='articledesign',
            name='header_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='records'),
        ),
    ]
