# Generated by Django 3.0.3 on 2020-04-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organization_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            bases=('core.record',),
        ),
    ]
