# Generated by Django 3.1.2 on 2021-01-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201222_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLoopsIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('relevant_construction', models.BooleanField(default=False)),
                ('relevant_biomass', models.BooleanField(default=False)),
                ('vision_element', models.IntegerField(choices=[(1, 'Local stakeholder actions'), (2, 'Circular business models and behavioural patterns'), (3, 'Closing material loops and reducing harmful resource use'), (4, 'Improving human well-being and reducing environmental impacts')], db_index=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CityLoopsIndicatorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('sector', models.IntegerField(choices=[(1, 'Construction and demolition waste'), (2, 'Biomass waste')], db_index=True)),
                ('scale', models.IntegerField(choices=[(1, 'City'), (2, 'Demonstration action'), (3, 'Sector')], db_index=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('baseline', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('accuracy', models.TextField(blank=True, null=True)),
                ('coverage', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.referencespace')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cityloopsindicator')),
            ],
        ),
    ]
