# Generated by Django 3.0.3 on 2020-03-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200312_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledesign',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='design', serialize=False, to='core.Article'),
        ),
    ]
