# Generated by Django 3.0.3 on 2020-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
