# Generated by Django 3.0.3 on 2020-03-13 10:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200312_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledesign',
            name='header_background',
        ),
        migrations.AddField(
            model_name='articledesign',
            name='header_texture',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='header_texture'),
        ),
        migrations.AlterField(
            model_name='articledesign',
            name='header_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='header_image'),
        ),
    ]
