# Generated by Django 3.1.2 on 2021-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210107_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdemand',
            name='availability',
            field=models.CharField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Occasionally', 'Occasionally available'), ('Short_term_use', 'Available short-term use'), ('Long_term_use', 'Available for long-term use')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
