# Generated by Django 3.1.2 on 2021-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
