# Generated by Django 3.1.2 on 2021-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210214_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityloopsindicator',
            name='mandatory_biomass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cityloopsindicator',
            name='mandatory_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cityloopsindicator',
            name='methodology_html',
            field=models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True),
        ),
    ]
