# Generated by Django 3.0.3 on 2020-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200426_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
