# Generated by Django 3.0.3 on 2020-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200313_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_site',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='youtube', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('conference', 'Conference'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('summerschool', 'Summer School'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default='http://example.org', max_length=255),
            preserve_default=False,
        ),
    ]
