# Generated by Django 3.0.3 on 2020-04-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200426_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, choices=[('academic', 'Academic'), ('theses', 'Theses'), ('reports', 'Reports'), ('multimedia', 'Multimedia')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('CH', 'Chinese'), ('FR', 'French'), ('GE', 'German'), ('NL', 'Dutch'), ('OT', 'Other')], max_length=2)),
                ('title_original_language', models.CharField(blank=True, max_length=255, null=True)),
                ('authorlist', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('abstract_original_language', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(blank=True, help_text='Only upload the file if you are the creator or you have permission to do so', null=True, upload_to='references')),
                ('open_access', models.NullBooleanField()),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deleted', 'Deleted')], db_index=True, max_length=8)),
                ('published_in', models.ForeignKey(blank=True, help_text='If the journal does not appear in the list, please leave empty and add the name in the comments', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Journal')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LibraryItemType')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
            bases=('core.record',),
        ),
    ]
