# Generated by Django 3.0.3 on 2020-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_libraryitem_libraryitemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='old_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Only used for the migration between old and new structure', null=True),
        ),
    ]
