# Generated by Django 3.1.2 on 2021-02-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210219_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name']},
        ),
    ]
