# Generated by Django 3.1.2 on 2021-02-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210221_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['code', 'name']},
        ),
    ]
