# Generated by Django 3.0.3 on 2020-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
