# Generated by Django 3.1.2 on 2021-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210221_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrelationship',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
