# Generated by Django 3.1.2 on 2021-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_recordrelationship_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdemand',
            name='availability',
            field=models.CharField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Occasionally', 'Occasionally available'), ('Short_term_use', 'Available short-term use'), ('Long_term_use', 'Available for long-term use')], max_length=50, null=True),
        ),
    ]
