# Generated by Django 3.1.2 on 2021-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_materialdemand_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdemand',
            name='days',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialdemand',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
