# Generated by Django 3.0.3 on 2020-04-28 18:28

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_news_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', '-id'], 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
