# Generated by Django 3.0.3 on 2020-04-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200428_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='introduction',
        ),
    ]
