# Generated by Django 3.1.2 on 2021-02-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210224_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('academic', 'Research Institution'), ('universities', 'Universities'), ('university_dep', 'University department/school/unit'), ('city_government', 'City Government'), ('regional_government', 'Regional Government'), ('national_government', 'National Government'), ('statistical_agency', 'Statistical Agency'), ('private_sector', 'Private Sector'), ('publisher', 'Publishers'), ('journal', 'Journal'), ('society', 'Academic Society'), ('ngo', 'NGO'), ('funding_program', 'Funding Programme'), ('other', 'Other')], max_length=20),
        ),
    ]
