# Generated by Django 3.0.3 on 2020-04-29 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('stafdb', '0016_referencespace_geocodes'),
        ('core', '0030_remove_news_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stafdb.ReferenceSpace')),
            ],
        ),
    ]
