# Generated by Django 3.0.3 on 2020-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_activatedspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatedspace',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
