# Generated by Django 3.1.2 on 2021-02-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210226_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='webpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.record'),
        ),
    ]
