# Generated by Django 3.0.3 on 2020-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0033_license_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedspace',
            name='slug',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='activatedspace',
            unique_together={('slug', 'site')},
        ),
    ]
