# Generated by Django 3.0.3 on 2020-04-29 18:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200429_0452'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forummessage',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='journal',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='libraryitem',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='record',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
