# Generated by Django 3.1.2 on 2021-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210228_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityloopsindicatorvalue',
            name='period_from',
        ),
        migrations.RemoveField(
            model_name='cityloopsindicatorvalue',
            name='period_to',
        ),
        migrations.AddField(
            model_name='cityloopsindicatorvalue',
            name='period',
            field=models.TextField(blank=True, null=True),
        ),
    ]
