# Generated by Django 3.0.3 on 2020-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200501_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
