# Generated by Django 3.0.3 on 2020-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_libraryitem_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
