# Generated by Django 3.1.2 on 2021-03-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210307_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Historic version'), (2, 'New draft version (unapproved)'), (3, 'Rejected version'), (4, 'Current version')], db_index=True),
        ),
    ]
