# Generated by Django 3.1.2 on 2021-03-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210326_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordhistory',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
