# Generated by Django 3.0.3 on 2020-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0024_auto_20200429_1843'),
        ('core', '0040_auto_20200501_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryitem',
            name='published_in',
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='spaces',
        ),
        migrations.AddField(
            model_name='record',
            name='spaces',
            field=models.ManyToManyField(blank=True, to='stafdb.ReferenceSpace'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('academic', 'Research Institution'), ('universities', 'Universities'), ('city_government', 'City Government'), ('regional_government', 'Regional Government'), ('national_government', 'National Government'), ('statistical_agency', 'Statistical Agency'), ('private_sector', 'Private Sector'), ('publisher', 'Publishers'), ('journal', 'Journal'), ('society', 'Academic Society'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
