# Generated by Django 3.1.2 on 2021-05-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cityloopsscareport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityloopsscareport',
            options={'ordering': ['city', 'sector']},
        ),
        migrations.RenameField(
            model_name='cityloopsscareport',
            old_name='space',
            new_name='city',
        ),
    ]
