# Generated by Django 3.0.3 on 2020-05-01 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200501_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('libraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LibraryItem')),
                ('embed_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('video_site', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('other', 'Other')], max_length=14)),
            ],
            bases=('core.libraryitem',),
            managers=[
                ('objects_including_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MOOCVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MOOCModule')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video')),
            ],
        ),
        migrations.AddField(
            model_name='moocprogress',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.MOOCVideo'),
            preserve_default=False,
        ),
    ]
