# Generated by Django 3.1.2 on 2021-05-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210526_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityloopsscareport',
            name='land_use_id',
        ),
        migrations.RemoveField(
            model_name='cityloopsscareport',
            name='population_id',
        ),
        migrations.AddField(
            model_name='cityloopsscareport',
            name='land_use_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_use', to='core.libraryitem'),
        ),
        migrations.AddField(
            model_name='cityloopsscareport',
            name='population_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='population', to='core.libraryitem'),
        ),
    ]
