# Generated by Django 3.1.2 on 2021-05-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210527_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityloopsscareport',
            name='actors_id',
        ),
        migrations.AddField(
            model_name='cityloopsscareport',
            name='actors_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='core.libraryitem'),
        ),
    ]
