# Generated by Django 3.0.3 on 2020-05-01 16:03

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0024_auto_20200429_1843'),
        ('sites', '0002_alter_domain_unique'),
        ('core', '0044_auto_20200501_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Webpage',
        ),
    ]
