# Generated by Django 3.0.3 on 2020-05-01 16:04

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200501_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebpageDesign',
            fields=[
                ('webpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='design', serialize=False, to='core.Webpage')),
                ('header', models.CharField(choices=[('full', 'Full header with title and subtitle'), ('small', 'Small header; menu only'), ('image', 'Image underneath menu')], default='full', max_length=6)),
                ('header_title', models.CharField(blank=True, max_length=100, null=True)),
                ('header_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('header_image', stdimage.models.StdImageField(blank=True, null=True, upload_to='header_image')),
                ('logo', stdimage.models.StdImageField(blank=True, null=True, upload_to='logos')),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleDesign',
        ),
    ]
