# Generated by Django 3.0.3 on 2020-05-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200501_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moocanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='moocmodule',
            name='mooc',
        ),
        migrations.RemoveField(
            model_name='moocmodulequestion',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moocmodulequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='moocprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moocprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moocprogress',
            name='video',
        ),
        migrations.RemoveField(
            model_name='moocquizanswers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='moocquizanswers',
            name='mooc',
        ),
        migrations.RemoveField(
            model_name='moocquizanswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='moocquizanswers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moocvideo',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moocvideo',
            name='video',
        ),
        migrations.DeleteModel(
            name='MOOC',
        ),
        migrations.DeleteModel(
            name='MOOCAnswer',
        ),
        migrations.DeleteModel(
            name='MOOCModule',
        ),
        migrations.DeleteModel(
            name='MOOCModuleQuestion',
        ),
        migrations.DeleteModel(
            name='MOOCProgress',
        ),
        migrations.DeleteModel(
            name='MOOCQuestion',
        ),
        migrations.DeleteModel(
            name='MOOCQuizAnswers',
        ),
        migrations.DeleteModel(
            name='MOOCVideo',
        ),
    ]
