# Generated by Django 3.1.2 on 2021-06-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210608_1126'),
        ('core', '0046_delete_dataset'),
    ]

    operations = [
    ]
