# Generated by Django 3.1.2 on 2021-06-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20210609_0534'),
        ('core', '0047_merge_20210609_0531'),
    ]

    operations = [
    ]
