# Generated by Django 3.0.3 on 2020-05-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
    ]
