# Generated by Django 3.0.3 on 2020-05-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_organization_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordrelationship',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordrelationship',
            name='record_secondary',
        ),
        migrations.AddField(
            model_name='recordrelationship',
            name='record_child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_child', to='core.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordrelationship',
            name='record_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_parent', to='core.Record'),
            preserve_default=False,
        ),
    ]
