# Generated by Django 3.1.2 on 2021-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210609_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityloopsscareport',
            name='quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityloopsscareport',
            name='quality_html',
            field=models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True),
        ),
        migrations.AddField(
            model_name='cityloopsscareport',
            name='sankey_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityloopsscareport',
            name='sankey_description_html',
            field=models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True),
        ),
    ]
