# Generated by Django 3.1.2 on 2021-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210617_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityloopsscareport',
            name='country_gdp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityloopsscareport',
            name='nuts2_gdp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityloopsscareport',
            name='nuts3_gdp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityloopsscareport',
            name='space_gdp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
