# Generated by Django 3.0.3 on 2020-05-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200501_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordrelationship',
            options={'verbose_name': 'relationship manager', 'verbose_name_plural': 'relationship manager'},
        ),
        migrations.AlterField(
            model_name='recordrelationship',
            name='record_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_list', to='core.Record'),
        ),
        migrations.AlterField(
            model_name='recordrelationship',
            name='record_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_list', to='core.Record'),
        ),
    ]
