# Generated by Django 3.1.2 on 2021-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210623_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdemand',
            name='estimate_value',
            field=models.IntegerField(blank=True, help_text='The total estimate value of the listing', null=True),
        ),
    ]
