# Generated by Django 3.0.3 on 2020-05-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200501_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['-year', 'name']},
        ),
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ['position', 'name']},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='title',
            new_name='name',
        ),
    ]
