# Generated by Django 3.0.3 on 2020-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafdb', '0024_auto_20200429_1843'),
        ('core', '0052_auto_20200501_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='stafdb.Sector'),
        ),
    ]
