# Generated by Django 3.1.2 on 2021-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_materialdemand_estimate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
