# Generated by Django 3.0.3 on 2020-05-03 09:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_record_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('discarded', 'Discarded'), ('on_hold', 'On Hold'), ('progress', 'In Progress')], default='open', max_length=14)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=4)),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=4)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People')),
                ('project', models.ForeignKey(blank=True, limit_choices_to={'is_internal': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workpieces', to='core.Project')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workpieces_list', to='core.Record')),
            ],
        ),
    ]
