# Generated by Django 3.1.2 on 2021-08-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20210804_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitemtype',
            name='bibtex_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
