# Generated by Django 3.1.2 on 2021-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_libraryitemtype_bibtex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to='core.People'),
        ),
    ]
