# Generated by Django 3.0.3 on 2020-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_workpiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpiece',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
