# Generated by Django 3.1.2 on 2021-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210916_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitemtype',
            name='ris_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
