# Generated by Django 3.1.2 on 2021-10-02 12:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210916_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTree',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tree_node', serialize=False, to='core.material')),
                ('ancestors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
