# Generated by Django 3.0.3 on 2020-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_workpiece_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpiece',
            name='type',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('data_entry', 'Data Entry'), ('data_review', 'Review of Data'), ('design', 'Design')], default='editorial', max_length=40),
            preserve_default=False,
        ),
    ]
