# Generated by Django 3.1.2 on 2021-10-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_materialtree'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialtree',
            table='core_material_tree',
        ),
    ]
