# Generated by Django 3.1.2 on 2021-10-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20211002_1251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialtree',
            table='stafdb_material_tree',
        ),
    ]
