# Generated by Django 3.1.2 on 2022-09-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20220902_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='has_private_documents',
        ),
    ]
