# Generated by Django 3.1.2 on 2021-10-02 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20211002_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTreeClosure',
            fields=[
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), primary_key=True, serialize=False, size=None)),
                ('depth', models.IntegerField()),
            ],
            options={
                'db_table': 'stafdb_material_tree_closure',
                'managed': False,
            },
        ),
    ]
