# Generated by Django 3.0.3 on 2020-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200503_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpiece',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workpiece',
            name='assigned_to',
            field=models.ManyToManyField(to='core.People'),
        ),
    ]
