# Generated by Django 3.1.2 on 2022-09-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_project_has_private_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataviz',
            options={'ordering': ['id']},
        ),
    ]
