# Generated by Django 3.1.2 on 2022-09-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20220902_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='secondary_chart',
            field=models.BooleanField(default=False),
        ),
    ]
