# Generated by Django 3.0.3 on 2020-05-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200503_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelationship',
        ),
    ]
