# Generated by Django 3.1.2 on 2022-09-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_dataviz_secondary_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataviz',
            old_name='secondary_chart',
            new_name='is_secondary',
        ),
    ]
