# Generated by Django 3.0.3 on 2020-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_delete_userrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='label',
            field=models.CharField(default='pending', max_length=255),
            preserve_default=False,
        ),
    ]
