# Generated by Django 3.0.3 on 2020-05-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200503_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name_plural': 'people'},
        ),
    ]
