# Generated by Django 3.1.2 on 2022-09-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20220902_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedspace',
            name='part_of_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_spaces', to='core.project'),
        ),
    ]
