# Generated by Django 3.1.2 on 2022-09-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_data_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedspace',
            name='part_of_project',
            field=models.ForeignKey(limit_choices_to={'is_data_project': True}, on_delete=django.db.models.deletion.CASCADE, related_name='activated_spaces', to='core.project'),
        ),
    ]
