# Generated by Django 3.1.2 on 2022-09-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20220922_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='part_of_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='core.project'),
        ),
    ]
