# Generated by Django 3.0.3 on 2020-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200503_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpiece',
            name='type',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('curation', 'Curation'), ('data_entry', 'Data Entry'), ('data_review', 'Review of Data'), ('design', 'Design'), ('quality_control', 'Quality Control')], max_length=40),
        ),
    ]
