# Generated by Django 3.0.3 on 2020-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200503_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='child_of',
            field=models.ManyToManyField(related_name='_record_child_of_+', through='core.RecordRelationship', to='core.Record'),
        ),
    ]
