# Generated by Django 3.1.2 on 2022-09-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20220922_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_on_moc',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libraryitem'),
        ),
        migrations.AlterField(
            model_name='referencespace',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.libraryitem'),
        ),
    ]
