# Generated by Django 3.0.3 on 2020-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_record_child_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='parent_to',
            field=models.ManyToManyField(related_name='_record_parent_to_+', through='core.RecordRelationship', to='core.Record'),
        ),
    ]
