# Generated by Django 3.0.3 on 2020-05-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_record_parent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='child_of',
            field=models.ManyToManyField(related_name='parent_of_child', through='core.RecordRelationship', to='core.Record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parent_to',
            field=models.ManyToManyField(related_name='child_of_parent', through='core.RecordRelationship', to='core.Record'),
        ),
    ]
