# Generated by Django 3.1.2 on 2022-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20220927_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_private_data',
            field=models.BooleanField(default=False, help_text='Whether or not this data portal manages provide documents and data. If not then we can simplify certain queries.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='show_on_moc',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not this is shown in the project section on the Metabolism of Cities website'),
        ),
    ]
