# Generated by Django 3.1.2 on 2022-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_libraryitem_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='json',
            field=models.JSONField(blank=True, help_text='Here we store the JSON representation needed for data visualizations', null=True),
        ),
    ]
