# Generated by Django 3.0.3 on 2020-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20200503_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='author_citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='bibtex_citation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
