# Generated by Django 3.1.2 on 2022-09-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_libraryitem_json_drilldown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryitem',
            name='json',
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='json_drilldown',
        ),
    ]
