# Generated by Django 3.1.2 on 2022-09-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20220928_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='end',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='timeframe_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
