# Generated by Django 3.0.3 on 2020-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200504_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesign',
            name='back_link',
            field=models.BooleanField(default=True),
        ),
    ]
