# Generated by Django 3.1.2 on 2022-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20220930_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['date_start', 'id']},
        ),
        migrations.RemoveField(
            model_name='data',
            name='timeframe',
        ),
        migrations.AlterField(
            model_name='data',
            name='date_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='dates_label',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TimePeriod',
        ),
    ]
