# Generated by Django 3.0.3 on 2020-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_projectdesign_back_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='parent',
        ),
        migrations.AddField(
            model_name='record',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
