# Generated by Django 3.0.3 on 2020-05-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200504_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='position',
        ),
        migrations.AddField(
            model_name='webpage',
            name='belongs_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_internal': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpages', to='core.Project'),
        ),
    ]
