# Generated by Django 4.1.2 on 2022-10-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_project_contributor_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.record'),
        ),
    ]
