# Generated by Django 3.0.3 on 2020-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20200504_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdesign',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
    ]
