# Generated by Django 3.0.3 on 2020-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20200505_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
