# Generated by Django 3.1.2 on 2022-10-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20221019_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityloopsucareport',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='core.libraryitem'),
        ),
    ]
