# Generated by Django 4.1.2 on 2023-04-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_cityloopsucareport_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('water', 'Water'), ('energy', 'Energy'), ('emissions', 'Greenhouse gas emissions'), ('materials', 'Materials'), ('stock', 'Stocks')], max_length=20)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='water')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.people')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
