# Generated by Django 3.0.3 on 2020-05-06 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0080_people_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpiece',
            name='type',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('curation', 'Curation'), ('data_entry', 'Data Entry'), ('data_review', 'Review of Data'), ('design', 'Design'), ('quality_control', 'Quality Control'), ('administrative', 'Administrative')], max_length=40),
        ),
    ]
