# Generated by Django 4.1.2 on 2023-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_watersystemcategory_watersystemfile_watersystemflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystemflow',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
