# Generated by Django 4.1.2 on 2023-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_watersystemflow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSystemSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='watersystemflow',
            options={'ordering': ['category', 'identifier', 'name']},
        ),
    ]
