# Generated by Django 3.0.3 on 2020-05-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
