# Generated by Django 4.1.2 on 2023-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_watersystemcategory_unit_watersystemdata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystemdata',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=5, null=True),
        ),
    ]
