# Generated by Django 3.0.3 on 2020-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_socialmedia_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpiece',
            name='type',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('curation', 'Curation'), ('data_entry', 'Data Entry'), ('data_review', 'Review of Data'), ('design', 'Design'), ('quality_control', 'Quality Control'), ('administrative', 'Administrative'), ('programming', 'Programming'), ('sec', 'Security')], max_length=40),
        ),
    ]
