# Generated by Django 4.1.2 on 2023-04-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_watersystemdata_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersystemdata',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.watersystemflow'),
        ),
    ]
