# Generated by Django 3.0.3 on 2020-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20200510_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpiece',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
