# Generated by Django 3.0.3 on 2020-05-13 17:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_workpiece_tags'),
    ]

    operations = [
        migrations.RenameModel("WorkPiece", "WorkLog")
    ]
