# Generated by Django 4.1.2 on 2023-04-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_watersystemnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersystemfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.watersystemcategory'),
        ),
        migrations.AlterField(
            model_name='watersystemnode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.watersystemcategory'),
        ),
    ]
