# Generated by Django 3.0.3 on 2020-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20200513_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='type',
            field=models.CharField(choices=[('data', 'Data'), ('editorial', 'Editorial'), ('participation', 'Participation'), ('moderation', 'Moderation'), ('programming', 'Programming'), ('design', 'Design'), ('administrative', 'Administrative'), ('data_entry', 'Data Entry'), ('data_processing', 'Data Processing'), ('quality_control', 'Quality Control'), ('sec', 'Security'), ('curation', 'Curation')], max_length=40),
        ),
    ]
