# Generated by Django 3.0.3 on 2020-05-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20200513_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Creating'), (2, 'Uploading'), (3, 'Reviewing'), (4, 'Curating'), (5, 'Sharing'), (6, 'Participating'), (7, 'Learning'), (8, 'Administering'), (9, 'Programming'), (10, 'Designing')])),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='worklog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.WorkActivity'),
        ),
    ]
