# Generated by Django 4.1.2 on 2023-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_watersystemfile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystemnode',
            name='level',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
