# Generated by Django 4.1.2 on 2023-04-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_watersystemflow_level_watersystemflow_part_of_flow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watersystemflow',
            options={'ordering': ['category', 'level', 'identifier', 'name']},
        ),
    ]
