# Generated by Django 3.0.3 on 2020-05-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20200513_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='default_project',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_internal': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
