# Generated by Django 4.1.2 on 2023-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_watersystemflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystemcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
