# Generated by Django 3.0.3 on 2020-05-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_workactivity_default_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workactivity',
            options={'verbose_name_plural': 'work activities'},
        ),
    ]
