# Generated by Django 4.1.2 on 2023-04-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_watersystemcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watersystemnode',
            options={'ordering': ['category', 'identifier']},
        ),
        migrations.AddField(
            model_name='watersystemflow',
            name='normal_width_calculation',
            field=models.BooleanField(default=False, help_text='Some flows are extraordinarily large and should NOT be used for calculating average widths'),
        ),
    ]
