# Generated by Django 3.0.3 on 2020-05-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20200513_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold')], db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('required_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, limit_choices_to={'is_internal': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('worktype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.WorkActivity')),
            ],
        ),
    ]
