# Generated by Django 4.1.2 on 2023-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_watersystemnode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersystemflow',
            name='normal_width_calculation',
            field=models.BooleanField(default=True, help_text='Some flows are extraordinarily large and should NOT be used for calculating average widths'),
        ),
    ]
