# Generated by Django 3.0.3 on 2020-05-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='assigned_to',
        ),
    ]
