# Generated by Django 4.1.2 on 2023-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_watersystemflow_normal_width_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystemfile',
            name='level',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
