# Generated by Django 3.0.3 on 2020-05-13 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_remove_worklog_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('discarded', 'Discarded'), ('on_hold', 'On Hold'), ('progress', 'In Progress')], default='open', max_length=14)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=4)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.WorkActivity')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.People')),
                ('part_of_project', models.ForeignKey(blank=True, limit_choices_to={'is_internal': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='core.Project')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_work', to='core.Record')),
            ],
            bases=('core.record',),
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
