# Generated by Django 4.1.2 on 2023-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_watersystemfile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystemfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
