# Generated by Django 3.0.3 on 2020-05-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20200513_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='content',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='WorkLog',
        ),
    ]
