# Generated by Django 4.1.2 on 2023-06-14 19:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_watersystemfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLoopsHandbookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True)),
                ('position', models.SmallIntegerField(blank=True, help_text='The position at which this page should appear in the menu', null=True)),
                ('level', models.SmallIntegerField(blank=True, help_text='Where in the hierarchy this page should be. Leave blank for a main menu item', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='watersystemfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.waterfile_path),
        ),
    ]
