# Generated by Django 3.0.3 on 2020-05-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20200513_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'work items'},
        ),
    ]
