# Generated by Django 3.0.3 on 2020-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20200513_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
