# Generated by Django 4.1.2 on 2023-11-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_watermaterialcategory_alter_watermaterial_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermaterial',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='watermaterial',
            name='color2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watermaterial',
            name='color3',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watermaterial',
            name='color4',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watermaterial',
            name='color5',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
