# Generated by Django 4.1.2 on 2025-04-01 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0104_watersystemfile_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='saved_by_users',
            field=models.ManyToManyField(blank=True, related_name='saved_library_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
