# Generated by Django 4.1.2 on 2025-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_datasettype_libraryitem_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='uploader_contact',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
