# Generated by Django 3.0.3 on 2020-05-14 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20200514_0527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='license',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='space',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='photo',
            name='libraryitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LibraryItem'),
            preserve_default=False,
        ),
    ]
