# Generated by Django 4.1.2 on 2025-03-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_libraryitem_uploader_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryitem',
            old_name='uploader_contact',
            new_name='contact_email',
        ),
    ]
