# Generated by Django 3.0.3 on 2020-05-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20200514_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.License'),
        ),
        migrations.AddField(
            model_name='photo',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
