# Generated by Django 3.0.3 on 2020-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20200514_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('deleted', 'Deleted')], db_index=True, help_text='Old field, do not use', max_length=8, null=True),
        ),
    ]
