# Generated by Django 3.0.3 on 2020-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20200514_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='worktype',
        ),
    ]
