# Generated by Django 3.0.3 on 2020-05-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_badge_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='worktype',
            field=models.ManyToManyField(blank=True, to='core.WorkActivity'),
        ),
    ]
