# Generated by Django 3.0.3 on 2020-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_badge_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
