# Generated by Django 3.0.3 on 2020-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_badge_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['code', 'type']},
        ),
    ]
