# Generated by Django 3.0.3 on 2020-05-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20200514_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workactivity',
            options={'ordering': ['name'], 'verbose_name_plural': 'work activities'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='project',
        ),
    ]
