# Generated by Django 3.0.3 on 2020-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_auto_20200514_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='projects',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_internal': True}, to='core.Project'),
        ),
    ]
