# Generated by Django 3.0.3 on 2020-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20200514_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_permission',
            field=models.BooleanField(default=False, help_text='Mark if this relationship is about giving people permissions in the system'),
        ),
    ]
