# Generated by Django 3.0.3 on 2020-05-15 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_relationship_is_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.UploadSession'),
        ),
    ]
