# Generated by Django 3.0.3 on 2020-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20200515_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='slug',
            field=models.SlugField(blank=True, help_text='Should only be set for permissions, and should only be modified by the programming team', max_length=20, null=True, unique=True),
        ),
    ]
