# Generated by Django 3.0.3 on 2020-05-15 11:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_relationship_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor_page',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
