# Generated by Django 3.0.3 on 2020-05-15 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_project_contributor_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='support_page',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
