# Generated by Django 3.0.3 on 2020-05-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_publicproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_finish_date',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
