# Generated by Django 3.0.3 on 2020-05-18 14:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20200518_1157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='site',
        ),
        migrations.AddField(
            model_name='news',
            name='projects',
            field=models.ManyToManyField(to='core.Project'),
        ),
    ]
