# Generated by Django 3.0.3 on 2020-05-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_auto_20200518_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='include_in_timeline',
            field=models.BooleanField(default=False),
        ),
    ]
