# Generated by Django 3.0.3 on 2020-05-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_remove_uploadsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='uploader',
            field=models.ForeignKey(default=3444, on_delete=django.db.models.deletion.CASCADE, to='core.People'),
            preserve_default=False,
        ),
    ]
