# Generated by Django 3.0.3 on 2020-05-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_uploadsession_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.Project'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpages', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='work',
            name='part_of_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='default_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
