# Generated by Django 3.0.3 on 2020-05-20 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20200519_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataArticle',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('category', models.IntegerField(choices=[(1, 'Local industries'), (2, 'Resource use'), (3, 'Material stock'), (4, 'Waste')], db_index=True)),
                ('sub_category', models.IntegerField(blank=True, choices=[(1, 'Manufacturing industries'), (2, 'Extractive industries'), (3, 'Other industries')], db_index=True, null=True)),
                ('completion', models.IntegerField(choices=[(1, 'Stub'), (2, 'Medium article'), (3, 'Complete article')])),
            ],
            bases=('core.record',),
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Historic version'), (2, 'New draft version (unapproved)'), (3, 'Rejected version')], db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_history', to='core.People')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.Record')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
