# Generated by Django 3.0.3 on 2020-05-21 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_dataarticle_part_of_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDataset',
            fields=[
                ('libraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LibraryItem')),
                ('data_year_start', models.IntegerField(blank=True, null=True)),
                ('data_year_end', models.IntegerField(blank=True, null=True)),
                ('update_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('api_type', models.CharField(blank=True, max_length=50, null=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('core.libraryitem',),
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
