# Generated by Django 3.0.3 on 2020-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_librarydataportal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarydataset',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='librarydataset',
            name='api_type',
        ),
        migrations.AddField(
            model_name='librarydataportal',
            name='has_api',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='librarydataset',
            name='data_interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='librarydataset',
            name='has_api',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
