# Generated by Django 3.0.3 on 2020-05-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20200521_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarydataportal',
            name='portal_software',
        ),
        migrations.AddField(
            model_name='librarydataportal',
            name='software',
            field=models.IntegerField(blank=True, choices=[(1, 'CKAN'), (2, 'DKAN'), (3, 'Junar'), (4, 'OpenDataSoft'), (5, 'sixcms'), (6, 'Socrata'), (7, 'terraCatalogue'), (8, 'Custom / inhouse implementation'), (9, 'Other platform'), (10, 'ArcGIS Open Data')], null=True),
        ),
    ]
