# Generated by Django 3.0.3 on 2020-05-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20200522_0804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordrelationship',
            unique_together={('record_parent', 'relationship', 'record_child')},
        ),
    ]
