# Generated by Django 3.0.3 on 2020-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20200522_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydataset',
            name='data_formats',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent_tag_id': 786}, related_name='library_datasets', to='core.Tag'),
        ),
    ]
