# Generated by Django 3.0.3 on 2020-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_librarydataset_data_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, help_text='Only include the icon name, not fa- classes --- see https://fontawesome.com/icons?d=gallery', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
