# Generated by Django 3.0.3 on 2020-05-23 19:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20200523_1917'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
