# Generated by Django 3.0.3 on 2020-05-24 05:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_auto_20200523_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='record',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
