# Generated by Django 3.0.3 on 2020-05-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20200524_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
