# Generated by Django 3.0.3 on 2020-05-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20200524_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('academic', 'Research Institution'), ('universities', 'Universities'), ('city_government', 'City Government'), ('regional_government', 'Regional Government'), ('national_government', 'National Government'), ('statistical_agency', 'Statistical Agency'), ('private_sector', 'Private Sector'), ('publisher', 'Publishers'), ('journal', 'Journal'), ('society', 'Academic Society'), ('ngo', 'NGO'), ('funding_program', 'Funding Programme'), ('other', 'Other')], max_length=20),
        ),
    ]
