# Generated by Django 3.0.3 on 2020-05-26 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20200524_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('attachments', models.ManyToManyField(to='core.Document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Record')),
            ],
            bases=('core.record',),
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='ForumMessage',
        ),
    ]
