# Generated by Django 3.0.3 on 2020-05-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_forumtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='part_of_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
