# Generated by Django 3.0.3 on 2020-05-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_forumtopic_part_of_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_created']},
        ),
    ]
