# Generated by Django 3.0.3 on 2020-06-08 07:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20200529_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocode',
            options={'base_manager_name': 'objects', 'ordering': ['depth', 'pk']},
        ),
        migrations.AlterModelManagers(
            name='geocode',
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
