# Generated by Django 3.0.3 on 2020-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_worksprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='type',
            field=models.IntegerField(choices=[(1, 'Creating'), (2, 'Uploading'), (3, 'Reviewing'), (4, 'Curating'), (5, 'Sharing'), (6, 'Participating'), (7, 'Learning'), (8, 'Administering'), (9, 'Programming'), (10, 'Designing'), (11, 'Communicating')], db_index=True),
        ),
    ]
