# Generated by Django 3.0.3 on 2020-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20200610_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
