# Generated by Django 3.0.3 on 2020-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20200610_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
