# Generated by Django 3.0.3 on 2020-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20200610_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='icon',
            field=models.CharField(blank=True, help_text='Only include the icon name, not fa- classes --- see https://fontawesome.com/icons?d=gallery', max_length=50, null=True),
        ),
    ]
