# Generated by Django 3.0.3 on 2020-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webpage',
            name='site_slug',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='site',
        ),
        migrations.AddField(
            model_name='webpage',
            name='type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], default='markdown', max_length=10),
        ),
    ]
