# Generated by Django 3.0.3 on 2020-06-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20200611_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='belongs_to',
            new_name='part_of_project',
        ),
    ]
