# Generated by Django 3.0.3 on 2020-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20200611_0825'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='webpage',
            constraint=models.UniqueConstraint(fields=('part_of_project', 'slug'), name='project_slug'),
        ),
    ]
