# Generated by Django 3.0.3 on 2020-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20200611_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mass'), (2, 'Volume'), (3, 'Count'), (4, 'Area'), (5, 'Energy'), (6, 'Length'), (7, 'Fraction'), (99, 'Other')], db_index=True, default=1),
        ),
    ]
