# Generated by Django 3.0.3 on 2020-06-11 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20200611_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDemand',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Record')),
                ('quantity', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
            bases=('core.record',),
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
