# Generated by Django 3.0.3 on 2020-06-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_materialdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdemand',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
            preserve_default=False,
        ),
    ]
