# Generated by Django 3.0.3 on 2020-06-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_materialdemand_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialdemand',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand', to='core.Record'),
        ),
    ]
