# Generated by Django 3.0.3 on 2020-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_auto_20200611_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='multiplication_factor',
            field=models.FloatField(blank=True, help_text='By which factor should we multiply this to get a quantity in the default unit for this type of measurement?', null=True),
        ),
    ]
