# Generated by Django 3.0.3 on 2020-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_auto_20200612_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdiagram',
            name='icon',
            field=models.CharField(blank=True, help_text='Only include the icon name, not fa- classes --- see https://fontawesome.com/icons?d=gallery', max_length=50, null=True),
        ),
    ]
