# Generated by Django 3.0.3 on 2020-06-14 17:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_flowdiagram_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=core.models.upload_directory),
        ),
    ]
