# Generated by Django 3.0.3 on 2020-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20200614_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesign',
            name='header_color',
            field=models.CharField(choices=[('dark', 'Dark background, light text'), ('light', 'Light background, dark text')], default='dark', max_length=6),
        ),
    ]
