# Generated by Django 3.0.6 on 2020-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_librarydataset_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
