# Generated by Django 3.0.6 on 2020-06-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_chat'),
        ('core', '0171_librarydataset_size'),
    ]

    operations = [
    ]
