# Generated by Django 3.0.6 on 2020-06-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_remove_work_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
