# Generated by Django 3.0.6 on 2020-06-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_auto_20200616_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channel', to='core.Record'),
        ),
    ]
