# Generated by Django 3.0.6 on 2020-06-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_work_url'),
        ('core', '0174_auto_20200617_0513'),
    ]

    operations = [
    ]
