# Generated by Django 3.0.6 on 2020-06-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_merge_20200621_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_list', to='core.People'),
        ),
    ]
