# Generated by Django 3.0.6 on 2020-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20200623_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurostatdb',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
