# Generated by Django 3.0.6 on 2020-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20200623_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurostatdb',
            name='has_no_meta_data',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
