# Generated by Django 3.0.6 on 2020-06-23 18:15

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_eurostatdb_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='project_screenshots'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_sentence',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
