# Generated by Django 3.0.6 on 2020-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_auto_20200623_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary_sentence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
