# Generated by Django 3.0.6 on 2020-06-24 05:29

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_auto_20200623_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=stdimage.models.StdImageField(blank=True, help_text='1280x1024 is best - do not include browser tabs/menus', null=True, upload_to='project_screenshots'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_sentence',
            field=models.CharField(blank=True, help_text='Describe the project in a single sentence', max_length=255, null=True),
        ),
    ]
