# Generated by Django 3.0.6 on 2020-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_publicproject_part_of_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('markdown_html', 'Markdown and HTML')], default='markdown', max_length=13),
        ),
    ]
