# Generated by Django 3.0.6 on 2020-06-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_auto_20200624_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to='core.Record'),
        ),
    ]
