# Generated by Django 3.0.6 on 2020-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_forumtopic_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
