# Generated by Django 3.0.6 on 2020-06-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_record_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='subscribers',
        ),
    ]
