# Generated by Django 3.0.6 on 2020-06-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_remove_record_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_list', to='core.Record')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_list', to='core.People')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='core.Subscribers', to='core.People'),
        ),
    ]
