# Generated by Django 3.0.6 on 2020-06-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_auto_20200626_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
