# Generated by Django 3.0.6 on 2020-06-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_record_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.People')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_people', to='core.Record')),
            ],
        ),
    ]
