# Generated by Django 3.0.6 on 2020-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_auto_20200626_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='is_starred',
            field=models.NullBooleanField(default=False),
        ),
    ]
