# Generated by Django 3.0.6 on 2020-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_forumtopic_is_starred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['-is_starred', '-last_update']},
        ),
    ]
