# Generated by Django 3.0.6 on 2020-06-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_auto_20200628_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtopic',
            options={},
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='last_update',
        ),
    ]
