# Generated by Django 3.0.6 on 2020-06-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_auto_20200628_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['-is_starred', '-last_update']},
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='last_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Message'),
        ),
    ]
