# Generated by Django 3.0.6 on 2020-06-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_auto_20200628_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='site',
        ),
    ]
