# Generated by Django 3.0.6 on 2020-06-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_remove_people_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
    ]
