# Generated by Django 3.0.6 on 2020-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_auto_20200629_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('conference', 'Conference'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('summerschool', 'Summer School'), ('other', 'Other'), ('training_outreach', 'Training and Outreach')], max_length=20, null=True),
        ),
    ]
