# Generated by Django 3.0.6 on 2020-06-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_auto_20200629_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksprint',
            options={'ordering': ['-start_date']},
        ),
    ]
