# Generated by Django 3.0.6 on 2020-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_auto_20200629_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycatalog',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_catalogs'),
        ),
    ]
