# Generated by Django 3.0.6 on 2020-07-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_workactivity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='last_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Message'),
        ),
    ]
