# Generated by Django 3.0.6 on 2020-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_auto_20200701_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydataset',
            name='activities',
            field=models.ManyToManyField(blank=True, to='core.Activity'),
        ),
    ]
