# Generated by Django 3.0.6 on 2020-07-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_librarydataset_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='materials',
            field=models.ManyToManyField(blank=True, to='core.Material'),
        ),
    ]
