# Generated by Django 3.0.6 on 2020-07-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_record_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcatalog',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_catalogs'),
        ),
    ]
