# Generated by Django 3.0.6 on 2020-07-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_auto_20200702_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='Document',
        ),
    ]
