# Generated by Django 3.0.6 on 2020-07-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_auto_20200702_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='original_name',
        ),
    ]
