# Generated by Django 3.0.6 on 2020-07-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_remove_document_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_site',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('ted', 'TED'), ('other', 'Other')], max_length=14),
        ),
    ]
