# Generated by Django 3.0.6 on 2020-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_auto_20200706_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description_html',
            field=models.TextField(blank=True, help_text='Do not edit... auto-generated by the system', null=True),
        ),
    ]
