# Generated by Django 3.0.6 on 2020-07-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_tag_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatedspace',
            name='part_of_project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activatedspace',
            unique_together={('slug', 'part_of_project')},
        ),
        migrations.RemoveField(
            model_name='activatedspace',
            name='site',
        ),
    ]
