# Generated by Django 3.0.6 on 2020-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_forumtopic_parent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='parent_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
