# Generated by Django 3.0.6 on 2020-07-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0225_auto_20200710_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryDataPortal',
            new_name='DataPortal',
        ),
        migrations.RenameModel(
            old_name='LibraryDataset',
            new_name='Dataset',
        ),
    ]
