# Generated by Django 3.0.6 on 2020-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_auto_20200712_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activatedspace',
            options={'ordering': ['space__name']},
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('ES', 'Spanish'), ('CH', 'Chinese'), ('FR', 'French'), ('GE', 'German'), ('NL', 'Dutch'), ('PT', 'Portuguese'), ('OT', 'Other')], default='EN', max_length=2, null=True),
        ),
    ]
