# Generated by Django 3.0.6 on 2020-07-15 15:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0227_auto_20200713_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_directory),
        ),
    ]
