# Generated by Django 3.0.6 on 2020-07-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_auto_20200715_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryitem',
            old_name='attachments',
            new_name='files',
        ),
    ]
