# Generated by Django 3.0.6 on 2020-07-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_auto_20200715_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_list', to='core.Record'),
        ),
    ]
