# Generated by Django 3.0.6 on 2020-07-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0230_document_attached_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryitem',
            name='files',
        ),
    ]
