# Generated by Django 3.0.6 on 2020-07-16 04:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_auto_20200716_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.upload_directory),
        ),
    ]
