# Generated by Django 3.0.6 on 2020-08-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_auto_20200805_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CourseQuestionAnswer'),
        ),
    ]
