# Generated by Django 3.0.6 on 2020-08-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0237_auto_20200805_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursequestion',
            old_name='name',
            new_name='question',
        ),
    ]
