# Generated by Django 3.0.6 on 2020-08-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_auto_20200805_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursequestionanswer',
            old_name='name',
            new_name='answer',
        ),
    ]
