# Generated by Django 3.0.6 on 2020-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
