# Generated by Django 3.0.6 on 2020-08-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['name']},
        ),
    ]
