# Generated by Django 3.0.6 on 2020-08-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_auto_20200807_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='type',
            field=models.IntegerField(choices=[(1, 'Video'), (2, 'Text'), (3, 'Exercise')], db_index=True, default=1),
        ),
    ]
