# Generated by Django 3.0.6 on 2020-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_recordrelationship_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurostatdb',
            name='is_duplicate',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
