# Generated by Django 3.0.6 on 2020-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_eurostatdb_is_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurostatdb',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
