# Generated by Django 3.0.6 on 2020-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_eurostatdb_url_overwrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurostatdb',
            name='url_overwrite',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
