# Generated by Django 3.0.6 on 2020-08-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_auto_20200811_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocodescheme',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='geocodescheme',
            name='type',
            field=models.IntegerField(choices=[(1, 'National subdivisions'), (2, 'Sectoral infrastructure'), (3, 'Administrative areas')], db_index=True, default=3),
        ),
    ]
