# Generated by Django 3.0.6 on 2020-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_auto_20200812_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurostatdb',
            name='spaces',
            field=models.ManyToManyField(blank=True, to='core.ReferenceSpace'),
        ),
    ]
