# Generated by Django 3.0.6 on 2020-08-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_eurostatdb_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
