# Generated by Django 3.0.6 on 2020-08-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_worksprint_work_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencespace',
            options={'ordering': ['name']},
        ),
    ]
