# Generated by Django 3.0.6 on 2020-08-21 06:53

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_auto_20200820_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='blurb',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='published',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='campaign',
            field=models.ForeignKey(default=1, limit_choices_to={'parent_tag_id': 927}, on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='socialmedia'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('discarded', 'Discarded'), ('ready', 'Ready for publication'), ('published', 'Published')], default='draft', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Record'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='platforms',
            field=models.ManyToManyField(to='core.SocialMediaPlatform'),
        ),
    ]
