# Generated by Django 3.0.6 on 2020-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_auto_20200821_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
