# Generated by Django 3.0.6 on 2020-08-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20200821_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedspace',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated', to='core.ReferenceSpace'),
        ),
    ]
