# Generated by Django 3.0.6 on 2020-09-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicproject',
            name='site',
        ),
    ]
