# Generated by Django 3.0.6 on 2020-09-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_auto_20200908_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterocollection',
            name='api',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoterocollection',
            name='zotero_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
