# Generated by Django 3.0.6 on 2020-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_zoteroitem_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesign',
            name='content_footer_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdesign',
            name='show_footer_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectdesign',
            name='show_footer_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectdesign',
            name='show_footer_3',
            field=models.BooleanField(default=True),
        ),
    ]
