# Generated by Django 3.0.6 on 2020-09-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0265_auto_20200915_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets', models.BooleanField()),
                ('news', models.BooleanField()),
                ('events', models.BooleanField()),
                ('publications', models.BooleanField()),
                ('dataviz', models.BooleanField()),
                ('multimedia', models.BooleanField()),
                ('projects', models.BooleanField()),
                ('theses', models.BooleanField()),
                ('site', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.People')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('reference_spaces', models.ManyToManyField(blank=True, to='core.ReferenceSpace')),
            ],
        ),
    ]
