# Generated by Django 3.0.6 on 2020-09-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
