# Generated by Django 3.0.6 on 2020-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0267_delete_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
