# Generated by Django 3.0.6 on 2020-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_auto_20200917_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dataarticle',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='dataarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
