# Generated by Django 3.0.6 on 2020-09-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_auto_20200917_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataArticle',
        ),
    ]
