# Generated by Django 3.0.6 on 2020-09-17 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_delete_dataarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataArticle',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.Record')),
                ('completion', models.IntegerField(choices=[(1, 'Stub'), (2, 'Medium article'), (3, 'Complete article')])),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('part_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            bases=('core.record',),
            managers=[
                ('objects_unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
