# Generated by Django 3.0.6 on 2020-09-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_auto_20200917_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterocollection',
            name='part_of_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
