# Generated by Django 3.0.6 on 2020-09-29 07:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0273_zoterocollection_part_of_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
