# Generated by Django 3.0.6 on 2020-09-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0274_referencespace_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='location',
        ),
        migrations.DeleteModel(
            name='ReferenceSpaceLocation',
        ),
    ]
