# Generated by Django 3.0.6 on 2020-09-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0275_auto_20200929_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LibraryItem'),
        ),
    ]
