# Generated by Django 3.0.6 on 2020-09-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_referencespace_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='slug',
        ),
        migrations.AlterField(
            model_name='referencespace',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_spaces', to='core.LibraryItem'),
        ),
    ]
