# Generated by Django 3.1.2 on 2020-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0278_libraryitem_geocodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zoteroitem',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
