# Generated by Django 3.1.2 on 2020-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0279_auto_20201005_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='is_starred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='open_access',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
